name: HideAndSeek
author: DaAmazingShit
version: 1.0-SNAPSHOT-1
description: Hide and Seek minigame for your Minecraft Beta Bukkit server!
main: pl.amazingshit.has.HideAndSeekReborn

commands:
    hns:
        usage: /<command>
        aliases: [hideandseek]
        description: |
            Hide and Seek - plugin help